#!/usr/bin/env python3
"""
Schema Quiz Content Adapter

Converte un file JSON di domande/schema in un file server/schema-data.ts
pronto per essere copiato nel progetto.

Usage:
    python adapt_questions.py input.json > output-file.ts
    
    # Poi copia output-file.ts in server/schema-data.ts del progetto

Il file JSON di input deve avere questa struttura (vedi templates/schema-data-template.json):
{
  "appName": "Titolo App",
  "totalSlots": 12,
  "allKeywords": ["parola1", "parola2", ...],
  "schemaRows": [
    {
      "id": "fase1",
      "phaseLabel": "FASE 1 — TITOLO",
      "phaseSubtitle": "Sottotitolo",
      "color": "#8B1A1A",
      "slots": ["keyword1", "keyword2"]
    }
  ]
}

Lo script genera automaticamente:
- TypeScript interfaces
- TOTAL_SLOTS constant
- ALL_KEYWORDS array
- SCHEMA_ROWS array  
- buildSchemaSlots() function
- shuffle() function
"""

import json
import sys
import textwrap
from typing import Any


def validate_input(data: dict) -> None:
    """Validate the input JSON structure."""
    required = ["appName", "totalSlots", "allKeywords", "schemaRows"]
    for field in required:
        if field not in data:
            raise ValueError(f"Campo obbligatorio mancante: '{field}'")

    if not isinstance(data["allKeywords"], list) or len(data["allKeywords"]) < 2:
        raise ValueError("allKeywords deve essere un array con almeno 2 elementi")

    if not isinstance(data["schemaRows"], list) or len(data["schemaRows"]) < 1:
        raise ValueError("schemaRows deve essere un array con almeno 1 elemento")

    for row in data["schemaRows"]:
        for field in ["id", "phaseLabel", "color", "slots"]:
            if field not in row:
                raise ValueError(f"schemaRows: campo '{field}' mancante in riga: {json.dumps(row)}")
        if not isinstance(row["slots"], list) or len(row["slots"]) < 1:
            raise ValueError(f"schemaRows: 'slots' deve essere un array non vuoto in riga: {row['id']}")
    
    # Validate all keywords exist
    all_kws = set(data["allKeywords"])
    for row in data["schemaRows"]:
        for slot in row["slots"]:
            if slot not in all_kws:
                raise ValueError(f"Keyword '{slot}' in riga '{row['id']}' non trovata in allKeywords")


def generate_typescript(data: dict) -> str:
    """Generate the TypeScript source code."""
    
    interface_lines = [
        '/**',
        f' * Schema data for the interactive {data["appName"]} analysis.',
        ' * AUTO-GENERATED by schema-quiz-builder adapt_questions.py',
        ' * Do not edit manually — re-run the script instead.',
        ' */',
        '',
        'export interface SchemaRow {',
        '  id: string;',
        '  phaseLabel: string;',
        '  phaseSubtitle?: string;',
        '  color: string;',
        '  slots: string[];',
        '}',
        '',
        'export interface SchemaSlot {',
        '  id: string;',
        '  rowId: string;',
        '  phaseLabel: string;',
        '  phaseSubtitle?: string;',
        '  phaseColor: string;',
        '  correctAnswer: string;',
        '  options: string[];',
        '}',
        '',
    ]

    # TOTAL_SLOTS
    total_lines = [
        f'export const TOTAL_SLOTS = {data["totalSlots"]};',
        '',
    ]

    # ALL_KEYWORDS
    kw_lines = [
        '/**',
        f' * All {len(data["allKeywords"])} correct keywords — same across every dropdown in every phase.',
        ' */',
        f'export const ALL_KEYWORDS: string[] = [',
    ]
    for kw in data["allKeywords"]:
        escaped = json.dumps(kw)
        kw_lines.append(f'  {escaped},')
    kw_lines.append('];')
    kw_lines.append('')

    # SCHEMA_ROWS
    rows_lines = [
        '/**',
        f' * The {len(data["schemaRows"])} rows of the schema, with colors.',
        ' */',
        f'export const SCHEMA_ROWS: SchemaRow[] = [',
    ]
    for row in data["schemaRows"]:
        phase_subtitle = ""
        if row.get("phaseSubtitle"):
            phase_subtitle = f'\n    phaseSubtitle: {json.dumps(row["phaseSubtitle"])},'
        
        slots_list = ', '.join(json.dumps(s) for s in row["slots"])
        rows_lines.append(f'  {{')
        rows_lines.append(f'    id: {json.dumps(row["id"])},')
        rows_lines.append(f'    phaseLabel: {json.dumps(row["phaseLabel"])},{phase_subtitle}')
        rows_lines.append(f'    color: {json.dumps(row["color"])},')
        rows_lines.append(f'    slots: [{slots_list}],')
        rows_lines.append(f'  }},')
    rows_lines.append('];')
    rows_lines.append('')

    # Helper functions
    functions_lines = [
        '/**',
        ' * Fisher-Yates shuffle.',
        ' */',
        'export function shuffle<T>(arr: T[]): T[] {',
        '  const a = [...arr];',
        '  for (let i = a.length - 1; i > 0; i--) {',
        '    const j = Math.floor(Math.random() * (i + 1));',
        '    [a[i], a[j]] = [a[j], a[i]];',
        '  }',
        '  return a;',
        '}',
        '',
        '/**',
        f' * Build the flattened list of interactive slots for {data["appName"]}.',
        ' */',
        'export function buildSchemaSlots(): SchemaSlot[] {',
        '  const keywordsForAllSlots = shuffle(ALL_KEYWORDS);',
        '',
        '  return SCHEMA_ROWS.flatMap((row, rowIdx) =>',
        '    row.slots.map((keyword, idx) => ({',
        '      id: `${row.id}-slot-${idx}`,',
        '      rowId: row.id,',
        '      phaseLabel: row.phaseLabel,',
        '      phaseSubtitle: row.phaseSubtitle,',
        '      phaseColor: row.color,',
        '      correctAnswer: keyword,',
        '      options: keywordsForAllSlots,',
        '    }))',
        '  );',
        '}',
        '',
    ]

    return '\n'.join(interface_lines) + '\n'.join(total_lines) + '\n'.join(kw_lines) + '\n'.join(rows_lines) + '\n'.join(functions_lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: python adapt_questions.py input.json", file=sys.stderr)
        print("", file=sys.stderr)
        print("Genera un file server/schema-data.ts dal JSON di input.", file=sys.stderr)
        sys.exit(1)

    input_path = sys.argv[1]
    
    try:
        with open(input_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"Errore: File non trovato: {input_path}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Errore: JSON non valido in {input_path}: {e}", file=sys.stderr)
        sys.exit(1)

    try:
        validate_input(data)
    except ValueError as e:
        print(f"Errore di validazione: {e}", file=sys.stderr)
        sys.exit(1)

    output = generate_typescript(data)
    print("// Auto-generated by adapt_questions.py — do not edit manually")
    print(f'// Source: {input_path}')
    print(f'// Generated at: {__import__("datetime").datetime.now().isoformat()}')
    print()
    print(output)


if __name__ == "__main__":
    main()
